/**
 * Keep action names as constants in one file.  Use naming convention as below.
 */
export const PATIENTINFO_FETCH_DATA_SUCCESS= 'PATIENTINFO_FETCH_DATA_SUCCESS';
export const PATIENTINFO_FETCH_DATA_ERROR = 'PATIENTINFO_FETCH_DATA_ERROR';
export const ALLERGIES_FETCH_DATA_SUCCESS= 'ALLERGIES_FETCH_DATA_SUCCESS';
export const ALLERGIES_FETCH_DATA_ERROR = 'ALLERGIES_FETCH_DATA_ERROR';
