/**
 * Keep action names as constants in one file.  Use naming convention as below.
 */
export const CLINICALDOCS_TOGGLE_FUNCTION = 'CLINICALDOCS_TOGGLE_FUNCTION';
export const CLINICALDOCS_FETCH_DATA_SUCCESS= 'CLINICALDOCS_FETCH_DATA_SUCCESS';
export const CLINICALDOCS_FETCH_DATA_ERROR = 'CLINICALDOCS_FETCH_DATA_ERROR';
export const PATIENTINFO_FETCH_DATA_SUCCESS= 'PATIENTINFO_FETCH_DATA_SUCCESS';
export const PATIENTINFO_FETCH_DATA_ERROR = 'PATIENTINFO_FETCH_DATA_ERROR';
